// HOLOCRON — DMV study content (California, permit + road test)
// Sources: California Driver Handbook 2026 (dmv.ca.gov/portal/handbook/california-driver-handbook/)
// and the CA Vehicle Code. Paraphrased for study — always double-check against the official handbook.

// Change this to personalize the greeting.
const NAME = 'Emmett';

// ─── PERMIT QUESTIONS ───
// ~55 questions across the topics the CA permit test covers.
// Each has a short `explain` meant to teach, not just state the answer.
const QUESTIONS = [
  // ─── Right of Way ───
  { id: 'q1', topic: 'Right of Way',
    q: 'You approach a four-way stop at the same time as a driver on your right. Who has the right-of-way?',
    choices: [
      'You do — always yield left',
      'The driver on your right',
      'Whoever waves the other through',
      'You both go slowly at the same time',
    ], answer: 1,
    explain: 'At a four-way stop, when two drivers arrive at the same time, the driver on the right has the right-of-way.' },
  { id: 'q2', topic: 'Right of Way',
    q: 'A blind pedestrian carrying a white cane is crossing the street. You should:',
    choices: [
      'Honk to let them know you are there',
      'Drive around them slowly',
      'Stop and wait until they are safely across',
      'Wave them across',
    ], answer: 2,
    explain: 'Always stop for a pedestrian with a white cane or guide dog. Do not honk — it can be disorienting.' },
  { id: 'q3', topic: 'Right of Way',
    q: 'You are driving uphill on a narrow mountain road and meet a car coming downhill. Who should back up?',
    choices: [
      'The uphill driver',
      'The downhill driver',
      'Whoever is closer to a turnout',
      'The smaller vehicle',
    ], answer: 1,
    explain: 'On mountain roads the uphill vehicle has the right-of-way. The downhill vehicle is expected to back up.' },
  { id: 'q4', topic: 'Right of Way',
    q: 'You approach an intersection where the traffic signal is out (no lights at all). You should:',
    choices: [
      'Drive through carefully without stopping',
      'Treat it as an all-way stop',
      'Yield only to vehicles on your left',
      'Honk before entering',
    ], answer: 1,
    explain: 'A non-functioning traffic signal is treated as an all-way stop. Come to a full stop, then proceed in turn.' },
  { id: 'q5', topic: 'Right of Way',
    q: 'At a T-intersection without signs or signals:',
    choices: [
      'Traffic on the terminating road has priority',
      'Traffic on the through road has priority',
      'The vehicle on the right always goes first',
      'The vehicle on the left always goes first',
    ], answer: 1,
    explain: 'At an uncontrolled T-intersection, vehicles on the through road (the top of the T) have the right-of-way.' },
  { id: 'q6', topic: 'Right of Way',
    q: 'You are entering a roundabout. You should:',
    choices: [
      'Enter without slowing — roundabouts keep moving',
      'Yield to traffic already inside the roundabout',
      'Stop completely at the yield sign',
      'Yield only to vehicles on your right',
    ], answer: 1,
    explain: 'At a roundabout, yield to all traffic already in the circle. Travel counter-clockwise and signal when you exit.' },

  // ─── Speed Limits ───
  { id: 'q7', topic: 'Speed Limits',
    q: 'Unless otherwise posted, the speed limit in a California business or residential district is:',
    choices: ['15 mph', '25 mph', '35 mph', '45 mph'],
    answer: 1,
    explain: "CA's prima facie limit is 25 mph in business/residential districts unless posted otherwise." },
  { id: 'q8', topic: 'Speed Limits',
    q: 'The maximum speed limit on most California two-lane undivided highways is:',
    choices: ['45 mph', '55 mph', '65 mph', '70 mph'],
    answer: 1,
    explain: 'On two-lane undivided highways the max is 55 mph unless posted otherwise.' },
  { id: 'q9', topic: 'Speed Limits',
    q: 'The maximum speed limit on most California freeways is:',
    choices: ['55 mph', '60 mph', '65 mph', '75 mph'],
    answer: 2,
    explain: 'Most CA freeways are 65 mph. Some posted rural stretches go up to 70 mph.' },
  { id: 'q10', topic: 'Speed Limits',
    q: 'The Basic Speed Law in California says you must:',
    choices: [
      'Always drive the posted speed limit',
      'Never drive faster than is safe for current conditions',
      'Drive 5 mph below the posted limit in rain',
      'Match the speed of surrounding traffic',
    ], answer: 1,
    explain: "Posted limits are maximums for ideal conditions. The Basic Speed Law requires you drive no faster than is safe — regardless of the sign." },
  { id: 'q11', topic: 'Speed Limits',
    q: 'Near a blind railroad crossing with no signals, the speed limit is:',
    choices: ['5 mph', '15 mph', '25 mph', '35 mph'],
    answer: 1,
    explain: 'At blind intersections and uncontrolled railroad crossings, the prima facie limit is 15 mph.' },
  { id: 'q12', topic: 'Speed Limits',
    q: 'When driving on wet pavement, you should reduce your speed by about:',
    choices: ['0 mph — just drive carefully', '5 to 10 mph', '15 to 20 mph', 'Half the posted limit'],
    answer: 1,
    explain: 'Reduce by 5–10 mph on wet roads. Cut speed in half on packed snow and to ~5 mph on ice.' },

  // ─── Turns & Signals ───
  { id: 'q13', topic: 'Turns & Signals',
    q: 'You must signal continuously for at least how many feet before turning?',
    choices: ['50 feet', '100 feet', '150 feet', '200 feet'],
    answer: 1,
    explain: 'Signal at least 100 feet before a turn. Signal longer on highways where speeds are higher.' },
  { id: 'q14', topic: 'Turns & Signals',
    q: 'You may make a U-turn in a business district only:',
    choices: [
      'Anywhere, anytime',
      'At an intersection or on a divider that lets you, when no sign prohibits it',
      'Only at intersections with traffic lights',
      'Never',
    ], answer: 1,
    explain: 'In a business district you may U-turn at intersections or where openings in dividers allow — unless a sign prohibits it.' },
  { id: 'q15', topic: 'Turns & Signals',
    q: 'When making a right turn, you should:',
    choices: [
      'Stay as far right as possible',
      'Swing wide to the left first',
      'Stay in the middle of your lane',
      'Straddle two lanes',
    ], answer: 0,
    explain: 'Keep to the right-most lane or edge as you turn. Swinging wide confuses other drivers and can cause a collision.' },
  { id: 'q16', topic: 'Turns & Signals',
    q: 'When turning left at an intersection, you should yield to:',
    choices: [
      'Only other left-turning drivers',
      'Pedestrians and oncoming traffic',
      'Only pedestrians',
      'No one — you have a green arrow',
    ], answer: 1,
    explain: 'On a solid green (no arrow), left turns yield to oncoming traffic AND pedestrians in the crosswalk.' },

  // ─── Parking ───
  { id: 'q17', topic: 'Parking',
    q: 'When parallel parking, your wheels must be within how many inches of the curb?',
    choices: ['6 inches', '12 inches', '18 inches', '24 inches'],
    answer: 2,
    explain: '18 inches max. Farther than that and you risk a ticket — and lose points on the road test.' },
  { id: 'q18', topic: 'Parking',
    q: 'A red painted curb means:',
    choices: [
      'Parking allowed for 15 minutes',
      'Loading zone',
      'No stopping, standing, or parking',
      'Bus stop only',
    ], answer: 2,
    explain: 'Red = no stop, no stand, no park. It is often near fire hydrants or fire lanes.' },
  { id: 'q19', topic: 'Parking',
    q: 'A blue painted curb means:',
    choices: [
      'Loading zone',
      'Parking for persons with a disabled placard or plate',
      'Bus stop',
      'Short-term parking',
    ], answer: 1,
    explain: 'Blue = disabled parking. You need a valid placard or plate to park there.' },
  { id: 'q20', topic: 'Parking',
    q: 'When you park facing downhill with a curb, you should:',
    choices: [
      'Turn your wheels toward the curb and set the parking brake',
      'Turn your wheels away from the curb',
      'Leave wheels straight',
      'Shift into neutral',
    ], answer: 0,
    explain: 'Downhill: turn wheels INTO the curb so the car rolls into it if the brakes fail. Uphill with a curb: wheels turned AWAY from curb.' },

  // ─── DUI & Alcohol ───
  { id: 'q21', topic: 'DUI',
    q: 'If you are under 21, you can be charged with DUI at a BAC of:',
    choices: ['0.08% or higher', '0.05% or higher', '0.02% or higher', '0.01% or higher'],
    answer: 3,
    explain: 'California has zero tolerance under 21. A BAC of 0.01% is enough — one drink can do it.' },
  { id: 'q22', topic: 'DUI',
    q: 'For drivers 21 and older, the per se DUI BAC limit is:',
    choices: ['0.05%', '0.08%', '0.10%', '0.15%'],
    answer: 1,
    explain: '0.08% is the legal limit for drivers 21+. Commercial drivers are held to 0.04%.' },
  { id: 'q23', topic: 'DUI',
    q: 'California\'s "implied consent" law means:',
    choices: [
      'You can refuse all tests without penalty',
      'By driving in CA, you consent to breath, blood, or urine tests if arrested for DUI',
      'You must take a test only after a conviction',
      'You can choose which test you take at any time',
    ], answer: 1,
    explain: 'Driving in CA = implied consent. Refusing a chemical test after a DUI arrest = one-year license suspension automatically.' },
  { id: 'q24', topic: 'DUI',
    q: 'An open container of alcohol may be stored in:',
    choices: [
      'The cupholder',
      'The glove box',
      'The trunk (or behind the last row of seats in a vehicle with no trunk)',
      'The back seat',
    ], answer: 2,
    explain: 'Open containers go in the trunk. Not the glove box, not the cupholder. Not even sealed bottles if they have been opened.' },
  { id: 'q25', topic: 'DUI',
    q: 'A first DUI conviction can result in all of the following EXCEPT:',
    choices: [
      'Up to six months in jail',
      'License suspension',
      'Mandatory DUI school',
      'A permanent ban on ever driving again',
    ], answer: 3,
    explain: 'Penalties include jail, fines, license suspension, DUI school, and sometimes an ignition interlock. A permanent ban is not automatic from a first offense.' },

  // ─── Hands-Free / Cell Phones ───
  { id: 'q26', topic: 'Hands-Free Law',
    q: 'Drivers under 18 in California may use a cell phone while driving:',
    choices: [
      'Hands-free only',
      'On speakerphone only',
      'Not at all — not even hands-free',
      'Only at red lights',
    ], answer: 2,
    explain: 'Under 18: no cell phone use at all while driving. Even hands-free is prohibited except for emergencies.' },
  { id: 'q27', topic: 'Hands-Free Law',
    q: 'Drivers 18 and older may use a cell phone while driving:',
    choices: [
      'Any way they want',
      'Hands-free only (voice-operated or speakerphone)',
      'Only to call 911',
      'Only while stopped',
    ], answer: 1,
    explain: 'Adults 18+ may use a phone only hands-free — no holding the phone to your ear, no texting.' },
  { id: 'q28', topic: 'Hands-Free Law',
    q: 'Texting while driving in California is:',
    choices: [
      'Legal at red lights',
      'Legal for drivers over 18',
      'Illegal for all drivers',
      'Legal with voice-to-text for all drivers',
    ], answer: 2,
    explain: 'Texting while driving is illegal for all ages. Voice-to-text is allowed hands-free for 18+ only.' },

  // ─── Headlights ───
  { id: 'q29', topic: 'Headlights',
    q: 'In California you must turn on your headlights:',
    choices: [
      'Only at night',
      'Whenever your windshield wipers are in continuous use',
      'Only during rain',
      'Only when visibility is under 100 feet',
    ], answer: 1,
    explain: 'CA\'s "wipers on = lights on" law. Also required 30 minutes after sunset to 30 minutes before sunrise, and in low visibility.' },
  { id: 'q30', topic: 'Headlights',
    q: 'You should dim your high beams when:',
    choices: [
      'You are more than 1000 feet behind another car',
      'You are within 500 feet of an oncoming car or following within 300 feet of another car',
      'You enter a tunnel',
      'There is any other traffic anywhere on the road',
    ], answer: 1,
    explain: 'Dim high beams within 500 ft of oncoming traffic, or within 300 ft when following another car. Blinding other drivers is a citation.' },
  { id: 'q31', topic: 'Headlights',
    q: 'In heavy fog you should use:',
    choices: [
      'High beams for maximum visibility',
      'Low beams (or fog lights if equipped)',
      'Only parking lights',
      'Hazard lights only',
    ], answer: 1,
    explain: 'High beams reflect off fog and make it worse. Use low beams or fog lights and slow down.' },

  // ─── Following Distance ───
  { id: 'q32', topic: 'Following Distance',
    q: 'The minimum recommended following distance in good weather is:',
    choices: ['1 second', '2 seconds', '3 seconds', '5 seconds'],
    answer: 2,
    explain: 'Use the 3-second rule. Pick a fixed point, count: "one thousand one, one thousand two, one thousand three." If you pass the point before you finish, back off.' },
  { id: 'q33', topic: 'Following Distance',
    q: 'When following a motorcycle, you should:',
    choices: [
      'Follow at the same distance as a car',
      'Allow extra following distance (at least 4 seconds)',
      'Follow more closely so they see you',
      'Pass as soon as possible',
    ], answer: 1,
    explain: 'Motorcycles can stop faster than cars and are harder to see. Leave at least 4 seconds.' },
  { id: 'q34', topic: 'Following Distance',
    q: 'In rain or on wet pavement, your following distance should be:',
    choices: [
      'The same as on dry pavement',
      'Shorter so you can see better',
      'At least doubled (6+ seconds)',
      '1 second',
    ], answer: 2,
    explain: 'Double the 3-second rule to 6+ on wet roads. Triple it in snow or ice.' },

  // ─── School Zones & Pedestrians ───
  { id: 'q35', topic: 'School Zones',
    q: 'When children are present in a school zone, the speed limit is usually:',
    choices: ['15 mph', '20 mph', '25 mph', '35 mph'],
    answer: 2,
    explain: '25 mph is standard in CA school zones when children are present. Some zones post a lower limit (15 mph).' },
  { id: 'q36', topic: 'School Zones',
    q: 'A school bus is stopped ahead on a two-lane undivided road with its red lights flashing. You should:',
    choices: [
      'Pass carefully on the left',
      'Stop until the red lights stop flashing',
      'Slow to 15 mph and pass',
      'Honk to get the bus moving',
    ], answer: 1,
    explain: 'On an undivided road, traffic in BOTH directions must stop for a school bus with red lights flashing, until the lights stop.' },
  { id: 'q37', topic: 'Pedestrians',
    q: 'A pedestrian is in a crosswalk without traffic signals. You should:',
    choices: [
      'Honk so they move faster',
      'Yield the right-of-way and stop',
      'Drive around them',
      'Continue at the same speed',
    ], answer: 1,
    explain: 'Yield to pedestrians in any crosswalk — marked or unmarked. Never pass a car stopped at a crosswalk; they might be stopped for a pedestrian you can\'t see.' },

  // ─── Emergency Vehicles ───
  { id: 'q38', topic: 'Emergency Vehicles',
    q: 'When an emergency vehicle with lights and siren is approaching, you should:',
    choices: [
      'Speed up to get out of the way',
      'Pull to the right edge of the road and stop',
      'Stop immediately in your lane',
      'Continue at the same speed',
    ], answer: 1,
    explain: 'Pull to the right and stop until the emergency vehicle passes. If you\'re in an intersection, clear the intersection first, THEN pull right and stop.' },
  { id: 'q39', topic: 'Emergency Vehicles',
    q: 'You may follow an emergency vehicle (fire truck, ambulance) no closer than:',
    choices: ['100 feet', '200 feet', '300 feet', '500 feet'],
    answer: 2,
    explain: 'Stay at least 300 feet behind any emergency vehicle responding to a call. Following closer is illegal.' },
  { id: 'q40', topic: 'Emergency Vehicles',
    q: 'California\'s "Move Over" law requires you to:',
    choices: [
      'Pull over when you see any vehicle with hazard lights',
      'Move over one lane (or slow down) when passing a stopped emergency or Caltrans vehicle with flashing lights',
      'Stop for any vehicle parked on the shoulder',
      'Honk when passing an emergency vehicle',
    ], answer: 1,
    explain: 'Move over one lane when safe — or slow down if you can\'t — when passing stopped emergency vehicles, tow trucks, or Caltrans with lights flashing.' },

  // ─── Lane Changes & Passing ───
  { id: 'q41', topic: 'Lane Changes',
    q: 'Before changing lanes, after checking your mirrors you should:',
    choices: [
      'Honk to warn other drivers',
      'Look over your shoulder to check your blind spot',
      'Flash your high beams',
      'Speed up first',
    ], answer: 1,
    explain: "Mirrors don't cover your blind spot. Always do a head-turn shoulder check before changing lanes." },
  { id: 'q42', topic: 'Lane Changes',
    q: 'A solid yellow line on your side of the road means:',
    choices: [
      'You may pass when safe',
      'No passing',
      'Passing allowed only in emergencies',
      'Parking allowed',
    ], answer: 1,
    explain: 'Solid yellow = do not cross to pass. Dashed yellow means passing is allowed when safe.' },
  { id: 'q43', topic: 'Lane Changes',
    q: 'Double solid yellow lines in the middle of the road mean:',
    choices: [
      'Passing allowed for both directions',
      'No passing for either direction',
      'Passing allowed with caution',
      'Left turns only',
    ], answer: 1,
    explain: 'Two solid yellow lines = no passing either direction. You may still cross to make a left turn into a driveway.' },

  // ─── Road Signs ───
  { id: 'q44', topic: 'Signs & Signals',
    q: 'A red octagonal sign always means:',
    choices: [
      'Yield',
      'Stop',
      'Do not enter',
      'Warning',
    ], answer: 1,
    explain: 'Octagons are used for only one sign: STOP. Come to a full stop at the limit line or crosswalk before proceeding.' },
  { id: 'q45', topic: 'Signs & Signals',
    q: 'A yellow diamond-shaped sign usually means:',
    choices: [
      'Regulatory rule — must obey',
      'Warning of something ahead',
      'Construction zone',
      'School zone',
    ], answer: 1,
    explain: 'Yellow diamonds warn of conditions ahead: curves, merges, animals, bumps, etc. Slow down and watch for the hazard.' },
  { id: 'q46', topic: 'Signs & Signals',
    q: 'A pentagon-shaped sign means:',
    choices: [
      'Stop ahead',
      'Railroad crossing',
      'School zone or school crossing',
      'No passing zone',
    ], answer: 2,
    explain: 'The five-sided pentagon is always a school zone / school crossing sign.' },
  { id: 'q47', topic: 'Signs & Signals',
    q: 'A flashing yellow traffic light means:',
    choices: [
      'Stop, then proceed',
      'Slow down and proceed with caution',
      'Treat as a red light',
      'Traffic signal broken — turn around',
    ], answer: 1,
    explain: 'Flashing yellow = caution, slow down. Flashing red = stop, then proceed like a stop sign.' },

  // ─── Traffic Signals ───
  { id: 'q48', topic: 'Signs & Signals',
    q: 'A steady yellow traffic light means:',
    choices: [
      'Speed up to clear the intersection',
      'Stop if you can do so safely; otherwise cross cautiously',
      'Turn left only',
      'Proceed with caution at any speed',
    ], answer: 1,
    explain: 'Yellow = warning that red is coming. Stop if you can; if stopping would be unsafe, clear the intersection carefully.' },
  { id: 'q49', topic: 'Signs & Signals',
    q: 'You may turn right on a red light when:',
    choices: [
      'Never — red means stop',
      'Always, as long as no cars are coming',
      'After a full stop, yielding to pedestrians and traffic, unless a sign says NO TURN ON RED',
      'Only with a green arrow',
    ], answer: 2,
    explain: 'Full stop first, then yield to pedestrians and cross traffic, then turn — unless a "NO TURN ON RED" sign is posted.' },

  // ─── Young Drivers (Provisional License) ───
  { id: 'q50', topic: 'Provisional License',
    q: 'During the first 12 months of your CA provisional license (under 18), you may NOT:',
    choices: [
      'Drive on freeways',
      'Carry passengers under 20 unless a licensed parent/guardian 25+ is present',
      'Drive to school',
      'Drive out of state',
    ], answer: 1,
    explain: 'First 12 months: no passengers under 20, and no driving between 11pm and 5am — unless a licensed parent/guardian 25+ is riding along (or other listed exceptions).' },
  { id: 'q51', topic: 'Provisional License',
    q: 'During the first 12 months, a provisional licensee under 18 may not drive between:',
    choices: [
      '9pm and 6am',
      '10pm and 5am',
      '11pm and 5am',
      'Midnight and 4am',
    ], answer: 2,
    explain: 'No driving from 11pm to 5am during the first 12 months — unless accompanied by a licensed parent, guardian, or driver 25+, or for listed exceptions (work, school, medical).' },
  { id: 'q52', topic: 'Provisional License',
    q: 'To get a CA driver license at 16, a provisional-permit holder must have completed at least how many hours of supervised driving practice?',
    choices: ['20 hours', '30 hours', '50 hours', '100 hours'],
    answer: 2,
    explain: '50 total hours of supervised driving, with at least 10 of those at night, before taking the driving test at 16.' },

  // ─── Misc Safety / Sharing the Road ───
  { id: 'q53', topic: 'Sharing the Road',
    q: 'When passing a bicyclist on a two-lane road, you should give them:',
    choices: [
      'At least 1 foot',
      'At least 3 feet of clearance',
      'Half the lane',
      'No clearance is required',
    ], answer: 1,
    explain: 'CA\'s 3-Feet-for-Safety Act: leave at least 3 feet between your car and a bicyclist when passing.' },
  { id: 'q54', topic: 'Sharing the Road',
    q: 'You are approaching a stopped school bus with red lights flashing on a divided highway (with a median). You should:',
    choices: [
      'Stop — you always stop for a school bus',
      'Slow to 15 mph',
      'You are not required to stop if you are on the other side of a divided highway',
      'Pass only on the right',
    ], answer: 2,
    explain: 'On a divided highway with a physical median, oncoming traffic is NOT required to stop. On undivided roads, both directions must stop.' },
  { id: 'q55', topic: 'Collisions',
    q: 'If you are in a collision in CA, you must report it to the DMV (form SR-1) within 10 days if there is:',
    choices: [
      'Any damage at all',
      'Injury to anyone, any death, or property damage over $1,000',
      'Only a fatality',
      'Only damage to your own car',
    ], answer: 1,
    explain: 'File an SR-1 within 10 days of any crash with injury, death, or property damage over $1,000 — regardless of fault.' },
  { id: 'q56', topic: 'Collisions',
    q: "California's Financial Responsibility (insurance) minimums are at least:",
    choices: [
      '$5k bodily injury / $5k property damage',
      '$15k per person / $30k per accident bodily injury / $5k property damage',
      '$50k per person / $100k per accident / $10k property',
      'No minimum — CA is optional',
    ], answer: 1,
    explain: 'CA minimums: 15/30/5 — $15k bodily injury per person, $30k per accident, $5k property damage. You must carry proof in your car.' },

  // ─── Seat Belts & Child Safety ───
  { id: 'q57', topic: 'Seat Belts',
    q: 'In California, who in the vehicle is required to wear a seat belt?',
    choices: [
      'Only the driver',
      'Driver and front passengers only',
      'Everyone in the vehicle, in every seating position',
      'Only adults over 18',
    ], answer: 2,
    explain: 'Every occupant in every seat must be belted. The driver is ticketed for any unbelted passenger under 16.' },
  { id: 'q58', topic: 'Child Safety',
    q: 'A child must ride in a rear-facing car seat in California until they are at least:',
    choices: [
      '1 year old or 20 lbs',
      '2 years old (and under 40 lbs and 40 inches)',
      '4 years old',
      '6 years old',
    ], answer: 1,
    explain: 'Rear-facing until 2 AND under 40 lbs AND under 40 in. — exceed any one of those and forward-facing is allowed.' },
  { id: 'q59', topic: 'Child Safety',
    q: 'Children must ride in the back seat using a booster or car seat until they are at least:',
    choices: [
      'Age 6',
      "Age 8 or 4 feet 9 inches tall (whichever comes first)",
      'Age 10',
      'Age 12 and 100 lbs',
    ], answer: 1,
    explain: 'CA requires a booster (or car seat) until age 8 OR 4\'9" — whichever comes first. Back seat only until age 8.' },

  // ─── Railroad Crossings ───
  { id: 'q60', topic: 'Railroad Crossings',
    q: 'You approach a railroad crossing and the gate is down with red lights flashing. You should:',
    choices: [
      'Stop, then drive around the gate if no train is visible',
      'Stop at least 15 feet from the nearest rail and wait until the gate rises AND lights stop',
      'Sound your horn and cross',
      'Continue at reduced speed',
    ], answer: 1,
    explain: 'Never drive around a lowered gate — it is illegal and often deadly. Wait for the gate to rise AND the lights to stop.' },
  { id: 'q61', topic: 'Railroad Crossings',
    q: 'You are approaching a railroad crossing and traffic is backed up on the other side. You should:',
    choices: [
      'Cross and hope the train holds off',
      'Wait until there is room for your entire vehicle on the other side before entering',
      'Stop on the tracks and wait',
      'Drive around slower cars',
    ], answer: 1,
    explain: 'Never enter a crossing unless you can fully clear it. Getting stuck on the tracks is one of the most fatal situations on the road.' },

  // ─── HOV / Lane Markings ───
  { id: 'q62', topic: 'HOV Lanes',
    q: 'To use a California HOV (carpool) lane during operating hours, you must usually have at least:',
    choices: [
      'One occupant',
      'Two occupants (or more, depending on the posted sign)',
      'Three occupants always',
      'A commercial license',
    ], answer: 1,
    explain: 'Most HOV lanes in CA require 2+ occupants; some require 3+. Always check the posted sign. Motorcycles and qualifying clean-air vehicles with decals also count.' },
  { id: 'q63', topic: 'HOV Lanes',
    q: 'You may enter or exit an HOV lane only:',
    choices: [
      'Anywhere along the lane',
      'Where the line is dashed or broken — not across a solid double yellow',
      'At freeway exits only',
      'Whenever another car is doing it',
    ], answer: 1,
    explain: 'Crossing the solid double yellow into/out of the HOV lane is a ticket. Enter only at the dashed-line openings.' },
  { id: 'q64', topic: 'Lane Markings',
    q: 'A two-way center left-turn lane (marked by solid and dashed yellow lines) may be used:',
    choices: [
      'For passing slower traffic',
      'Only to turn left, from either direction, with up to 200 feet of approach',
      'As a regular travel lane in light traffic',
      'Only for U-turns',
    ], answer: 1,
    explain: 'It is a turn-only lane. You may be in it up to ~200 feet before your turn. Driving in it is a violation.' },
  { id: 'q65', topic: 'Lane Markings',
    q: 'A solid white line between lanes going in the same direction means:',
    choices: [
      'Lane changes are allowed',
      'Lane changes discouraged; cross only when necessary and safe',
      'No driving allowed',
      'Emergency vehicles only',
    ], answer: 1,
    explain: 'Dashed white = change freely. Solid white = stay in your lane unless you must change. Double solid white = never cross.' },

  // ─── Pedestrians (expanded) ───
  { id: 'q66', topic: 'Pedestrians',
    q: 'You are approaching a crosswalk and a car in the lane next to you has stopped. You should:',
    choices: [
      'Pass — the other car is probably just slow',
      'Also stop — that car may be yielding to a pedestrian you cannot yet see',
      'Sound the horn to clear traffic',
      'Change lanes and continue',
    ], answer: 1,
    explain: 'Never pass a vehicle stopped at a crosswalk. CVC 21951: they are likely yielding to a pedestrian you cannot see.' },

  // ─── 2026 New Laws ───
  { id: 'q67', topic: 'Emergency Vehicles',
    q: "California's 2026 updated Move Over law requires you to slow down and change lanes (when safe) when passing:",
    choices: [
      'Only stopped emergency vehicles',
      'Only Caltrans work trucks',
      'Any stationary vehicle displaying hazard lights, flares, or warning signs',
      'Only police cars',
    ], answer: 2,
    explain: 'SB 719 expanded Move Over in 2026 to any stopped vehicle displaying warning signals — not only emergency/Caltrans vehicles.' },
  { id: 'q68', topic: 'Parking',
    q: "California's 'daylighting' law prohibits stopping or parking within how many feet of the approach side of a crosswalk?",
    choices: ['5 feet', '10 feet', '20 feet', '50 feet'],
    answer: 2,
    explain: 'AB 413, enforced in 2025–2026: no stopping/standing/parking within 20 ft of the approach side of any marked or unmarked crosswalk — even without a red curb.' },

  // ─── Parking (more) ───
  { id: 'q69', topic: 'Parking',
    q: 'The minimum distance you must park from a fire hydrant is:',
    choices: ['5 feet', '10 feet', '15 feet', '25 feet'],
    answer: 2,
    explain: '15 feet of clearance from any fire hydrant (CVC 22514).' },
  { id: 'q70', topic: 'Parking',
    q: 'A green painted curb means:',
    choices: [
      'No parking at any time',
      'Parking for a limited time (time is posted on a sign)',
      'Loading zone for freight',
      'Passenger pickup only',
    ], answer: 1,
    explain: 'Green = time-limited parking. White = short stop for passenger pickup/drop-off or mail. Yellow = loading zone. Blue = disabled. Red = no stop.' },

  // ─── Drugs (beyond alcohol) ───
  { id: 'q71', topic: 'DUI',
    q: 'Which of the following can result in a DUI in California?',
    choices: [
      'Alcohol only',
      'Illegal drugs only',
      'Alcohol, illegal drugs, prescription medication, or OTC drugs that impair driving',
      'Only drugs listed on a prescription bottle',
    ], answer: 2,
    explain: 'CA DUI applies to ANY substance that impairs safe driving — including legal prescriptions (Benadryl, Ambien), cannabis, and OTC meds.' },
  { id: 'q72', topic: 'DUI',
    q: 'Where may you store an opened container of cannabis in your vehicle?',
    choices: [
      'Glove box',
      'Passenger footwell',
      'In the trunk, or a locked area not accessible to the driver',
      'Cup holder',
    ], answer: 2,
    explain: 'CA treats opened cannabis like opened alcohol: trunk or locked area only. Using cannabis while driving or riding is illegal.' },

  // ─── Emergencies / Fatigue ───
  { id: 'q73', topic: 'Safe Driving',
    q: 'The most effective response if you start to feel drowsy on a long drive is to:',
    choices: [
      'Open a window and turn up the music',
      'Drink coffee and keep going',
      'Pull off in a safe place and take a short nap (or stop driving for the day)',
      'Chew gum',
    ], answer: 2,
    explain: 'Drowsy driving produces reaction-time impairment similar to a 0.08 BAC. Caffeine and air buy minutes, not hours.' },
  { id: 'q74', topic: 'Emergencies',
    q: 'If your rear wheels start to skid while driving, you should:',
    choices: [
      'Slam the brakes hard',
      'Turn the wheel sharply the opposite direction',
      'Ease off the gas and steer where you want the front of the car to go',
      'Pull the parking brake',
    ], answer: 2,
    explain: 'Steer into the skid — the direction you want to go — and ease off the gas. Braking or over-correcting makes it worse.' },

  // ─── Sharing the Road ───
  { id: 'q75', topic: 'Sharing the Road',
    q: 'The safest place to drive around a large truck is:',
    choices: [
      'Directly behind so the driver can see you',
      'In any of the truck\'s blind spots ("no-zones")',
      "Where you can see the truck driver's face in the truck's side mirror",
      'Next to the cab',
    ], answer: 2,
    explain: 'If you cannot see the truck driver in their side mirror, they cannot see you. Trucks have large blind spots on all four sides.' },
  { id: 'q76', topic: 'Sharing the Road',
    q: 'On a narrow road where you cannot leave 3 feet of space when passing a bicyclist, you must:',
    choices: [
      'Honk and pass',
      'Slow to a safe speed and pass only when you can do so without endangering the bicyclist',
      'Pass on the right',
      'Tailgate until they move over',
    ], answer: 1,
    explain: 'Under AB 1909 / CVC 21760, if you cannot give 3 feet you must slow to a safe speed and pass only when safe — effectively a full-lane-change on narrow roads.' },

  // ─── Freeway ───
  { id: 'q77', topic: 'Freeway Driving',
    q: 'When merging onto a freeway from an on-ramp, you should:',
    choices: [
      'Stop at the end of the on-ramp and wait for a gap',
      'Use the ramp to reach freeway speed, then merge into an adequate gap',
      'Slow down to 40 mph to let others pass you',
      'Merge at any speed — freeway traffic will move over',
    ], answer: 1,
    explain: 'Stopping on an on-ramp causes rear-end crashes. Match freeway speed, check the blind spot, merge smoothly.' },

  // ─── Financial / DUI consequences ───
  { id: 'q78', topic: 'DUI',
    q: 'After a DUI conviction, California requires you to file proof of financial responsibility on:',
    choices: [
      'Form SR-1',
      'Form SR-22 (or SR-1P for non-owners)',
      'Form DL-44',
      'Form DMV-14',
    ], answer: 1,
    explain: 'SR-22 (or SR-1P) is the insurance certificate required after a DUI, uninsured at-fault crash, or suspension. Must be kept on file for 3 years.' },
];

// ─── ROAD SIGNS ───
const SIGNS = [
  { id: 'stop',          name: 'Stop',             shape: 'octagon',  color: '#d93540' },
  { id: 'yield',         name: 'Yield',            shape: 'triangle', color: '#d93540' },
  { id: 'dne',           name: 'Do Not Enter',     shape: 'circle',   color: '#d93540' },
  { id: 'wrongway',      name: 'Wrong Way',        shape: 'rect',     color: '#d93540' },
  { id: 'oneway',        name: 'One Way',          shape: 'rect',     color: '#111'    },
  { id: 'nouturn',       name: 'No U-Turn',        shape: 'rect',     color: '#fff'    },
  { id: 'noparking',     name: 'No Parking',       shape: 'circle',   color: '#d93540' },
  { id: 'speed',         name: 'Speed Limit',      shape: 'rect',     color: '#fff'    },
  { id: 'rr',            name: 'Railroad Crossing',shape: 'circle',   color: '#f5a623' },
  { id: 'curve',         name: 'Curve Ahead',      shape: 'diamond',  color: '#f5a623' },
  { id: 'merge',         name: 'Merge',            shape: 'diamond',  color: '#f5a623' },
  { id: 'stopahead',     name: 'Stop Ahead',       shape: 'diamond',  color: '#f5a623' },
  { id: 'school',        name: 'School Zone',      shape: 'pent',     color: '#f5c94d' },
  { id: 'ped',           name: 'Pedestrian',       shape: 'diamond',  color: '#39ff88' },
  { id: 'construction',  name: 'Work Zone',        shape: 'diamond',  color: '#ff8c1a' },
  { id: 'hov',           name: 'HOV Lane',         shape: 'rect',     color: '#fff'    },
];

// ─── ROAD TEST CHECKLIST ───
// Aligned to the CA DMV Driving Performance Evaluation (DL-32) scoring criteria.
const ROAD_TEST_CHECKLIST = [
  { id: 'c1',  section: 'Pre-Drive', title: 'Know where every control is',         detail: 'Wipers, defroster, hazard lights, parking brake, turn signals, emergency flashers. The examiner will point and ask.' },
  { id: 'c2',  section: 'Pre-Drive', title: 'Adjust mirrors & seat before you start', detail: 'All three mirrors. Seat close enough that you can fully press the brake pedal with your right foot.' },
  { id: 'c3',  section: 'Pre-Drive', title: 'Seatbelt ON before the engine goes on', detail: 'Buckle up before you even turn the key. Failing to wear a seatbelt is an automatic critical error.' },
  { id: 'c4',  section: 'Pre-Drive', title: 'Check brake and horn function',        detail: 'Light brake press before moving. Tap the horn when the examiner asks. Both must work.' },
  { id: 'c5',  section: 'Driving',   title: 'Both hands on the wheel at 9 and 3',   detail: 'Two hands on the wheel unless you are actively signaling or shifting. Keep them visible.' },
  { id: 'c6',  section: 'Driving',   title: 'Scan mirrors every 5 to 8 seconds',    detail: 'The examiner is watching for visible head movement. Make it obvious.' },
  { id: 'c7',  section: 'Driving',   title: 'Shoulder-check before every lane change', detail: 'Mirror + shoulder turn. Mirrors alone = points off.' },
  { id: 'c8',  section: 'Driving',   title: 'Signal at least 100 ft before every turn or lane change', detail: 'Signal early. Do not flip the blinker and turn at the same time.' },
  { id: 'c9',  section: 'Driving',   title: 'Stay in the correct lane through turns', detail: 'Right turn: stay right. Left turn: enter the lane closest to the centerline.' },
  { id: 'c10', section: 'Driving',   title: 'Match speed to the limit and conditions', detail: 'Do not go over the limit. Do not go more than 5–10 mph under it either.' },
  { id: 'c11', section: 'Driving',   title: 'Maintain 3-second following distance', detail: 'More in rain or behind big trucks and motorcycles.' },
  { id: 'c12', section: 'Maneuvers', title: 'Parallel park within 18 inches of the curb', detail: '4-move method. Take your time. Small adjustments are allowed and will not fail you.' },
  { id: 'c13', section: 'Maneuvers', title: 'Three-point turn with a head-check each move', detail: 'Signal. Look both ways at every direction change. Do not hit the curb.' },
  { id: 'c14', section: 'Maneuvers', title: 'Back up straight for 50 feet, slow and controlled', detail: 'Right arm over the passenger seat, look out the rear window. Do not steer too fast.' },
  { id: 'c15', section: 'Stops',     title: 'Come to a FULL stop at every stop sign', detail: 'Wheels stop rolling. One-Mississippi count. Then go.' },
  { id: 'c16', section: 'Stops',     title: 'Stop behind the limit line, not on it', detail: 'If there is no limit line, stop before the crosswalk. Not on it.' },
  { id: 'c17', section: 'Stops',     title: 'No coasting to a stop with the clutch in', detail: 'If you drive stick, keep the clutch engaged until the last moment. Coast-stopping is a point deduction.' },
  { id: 'c18', section: 'Pre-Drive', title: 'Demonstrate hand signals (left, right, slow/stop)', detail: 'The examiner will ask you to show them. Left arm straight out = left; arm up = right; arm down = slow/stop.' },
  { id: 'c19', section: 'Pre-Drive', title: 'Locate every control on command',      detail: 'Wipers, defroster, headlights, hazard lights, parking brake. The examiner points and asks. Miss 4 of 6 on items 9–14 = fail before you even start.' },
  { id: 'c20', section: 'Driving',   title: 'Phone out of reach for the entire test', detail: 'Touching or even glancing at a phone = critical error. Under 18: no phone use at all (CVC 23123.5). Put it in the glove box before the test starts.' },
  { id: 'c21', section: 'Driving',   title: 'Never more than 10 mph over OR under the limit without cause', detail: '10 mph either direction is a critical driving error. Match posted limit and flow — not timid, not aggressive.' },
  { id: 'c22', section: 'Driving',   title: 'Cancel your turn signal after every turn or lane change', detail: 'A stuck signal confuses other drivers. Self-canceling signals do not always cancel — check every time.' },
  { id: 'c23', section: 'Driving',   title: 'Keep wheels straight when stopped to turn left', detail: 'At a left-turn stop with oncoming traffic: wheels straight. If rear-ended with angled wheels, you are pushed into oncoming traffic. DL-32 scores this separately.' },
  { id: 'c24', section: 'Driving',   title: 'Lane changes: blind-spot check, signal before AND after', detail: 'Shoulder check → signal → gap → cancel. Mirror-only = automatic deduction.' },
  { id: 'c25', section: 'Driving',   title: 'Center the vehicle in the lane — do not straddle lines', detail: 'Lane position is scored on every road type. Hugging or crossing a line = deductions.' },
  { id: 'c26', section: 'Maneuvers', title: 'Back 3 vehicle lengths while staying within 3 ft of the curb', detail: 'Examiner pulls you to the curb and asks you to back up. Right arm over the passenger seat, head turned. Slow, controlled, straight.' },
  { id: 'c27', section: 'Stops',     title: 'Full stop behind the limit line before turning right on red', detail: 'A rolling right-on-red is a critical error — automatic fail. Full stop, yield to pedestrians and cross traffic, then turn.' },
];

// ─── DRIVING TIPS ───
const TIPS = [
  { id: 't1',  icon: 'eye',         title: 'Scan 12–15 seconds ahead',       body: "Look where you're going, not at your hood. The further you scan, the more time you have to react. Big mirrors every 5–8 seconds." },
  { id: 't2',  icon: 'shield',      title: "Assume they don't see you",      body: 'Defensive driving means expecting the other car to make the mistake. Always leave yourself an exit.' },
  { id: 't3',  icon: 'smartphone',  title: 'Put the phone in the glovebox',  body: 'Not the cupholder. Not face-down on your leg. Out of reach = out of mind. Under 18: no phone use at all, period.' },
  { id: 't4',  icon: 'moon',        title: 'Night driving: dim it all',      body: 'Dim the dashboard. Do not stare at oncoming headlights — look at the right edge line instead. Slow down, your headlights only reach about 350 ft.' },
  { id: 't5',  icon: 'cloud-rain',  title: 'First 10 minutes of rain = worst',body: 'Oil and water on the road make it slick. Double your following distance immediately. Turn on your headlights (it is the law — wipers on = lights on).' },
  { id: 't6',  icon: 'zap',         title: 'If you skid: steer into it',     body: "Ease off the gas. Don't slam the brake. Look where you want to go — the car follows your eyes." },
  { id: 't7',  icon: 'cloud-rain',  title: 'Hydroplaning: ease off, no brakes', body: 'If you feel the steering go light: take your foot off the gas and hold the wheel straight. Braking makes it worse.' },
  { id: 't8',  icon: 'car',         title: 'Blowout: hold the wheel, ease off gas', body: 'Do NOT slam the brakes — that puts you in a spin. Grip the wheel firmly, ease off the accelerator, and slow gradually to the shoulder.' },
  { id: 't9',  icon: 'target',      title: 'Merging onto the freeway: match traffic speed', body: 'Use the on-ramp to get up to speed, then merge smoothly. Merging at 40 when traffic is going 65 is how people die on freeways.' },
  { id: 't10', icon: 'shield',      title: 'Train crossings: never stop on the tracks', body: 'If traffic is backed up, wait until there is room ALL THE WAY across before you enter. Trains need a mile to stop and always win.' },
  { id: 't11', icon: 'clock',       title: 'Fatigue is as bad as drunk',     body: 'Yawning, drifting, missing exits = pull over. A 20-minute nap in a safe rest area beats a crash.' },
  { id: 't12', icon: 'eye',         title: 'Share the road with bicycles',   body: "CA law: 3 feet minimum when passing. They're not going away, they're faster than you think, and they are exposed." },
  { id: 't13', icon: 'eye',         title: 'Left-turn blind curve: watch BOTH ways',  body: "When turning left into a driveway or on a green light, watch oncoming traffic AND the pedestrian crosswalk across your path. About 40% of fatal pedestrian crashes happen on left turns." },
  { id: 't14', icon: 'zap',         title: 'Brake failure: pump, downshift, e-brake', body: "Pump the brake to try to build pressure. If nothing: downshift to low gear, then slowly apply the parking brake. Steer to a safe shoulder. Don't turn off the engine — you'll lose power steering." },
  { id: 't15', icon: 'zap',         title: 'Fire or smoke: get out, stay out',        body: "Pull to the right shoulder, turn off the engine, get everyone 100+ feet away, call 911. Don't open the hood if the fire is under it — you feed it oxygen." },
  { id: 't16', icon: 'eye',         title: "Animal in the road: don't swerve",        body: "Brake hard in a straight line. Swerving into oncoming traffic or off-road kills more drivers than hitting the animal. Hit it if you must." },
  { id: 't17', icon: 'car',         title: 'Truck turning right: stay OUT of its lane', body: "Trucks swing wide to make right turns. Never pass a truck on the right at an intersection — their rear wheels will eat your bumper (or you)." },
  { id: 't18', icon: 'shield',      title: 'Traffic stop: hands visible, window down',  body: "Pull right safely, turn off engine, hands on the wheel, window down, interior light on at night. Don't reach for license or registration until asked." },
];

Object.assign(window, { NAME, QUESTIONS, SIGNS, ROAD_TEST_CHECKLIST, TIPS });
